const actionTypes = {
  FLOWER_CURSOR: 'FLOWER_CURSOR',
  COLLAPSE_CURSOR: 'COLLAPSE_CURSOR',
  CHANGE_LOGO_COLOR: 'CHANGE_LOGO_COLOR',
  UPDATE_CONTENT_STATE: 'UPDATE_CONTENT_STATE',
};

export default actionTypes;
